export const AppErrorCodes = {
    AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    AUTH_INVALID_REFRESH_TOKEN_FORMAT: 'AUTH_INVALID_REFRESH_TOKEN_FORMAT',
    AUTH_INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_EMAIL_EXISTS: 'USER_EMAIL_EXISTS',
} as const;

export type AppErrorCode = typeof AppErrorCodes[keyof typeof AppErrorCodes];


